### Example JWT
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjExMjkxMzd9.0SUt-OJXWTFmyCLYJ_Tzs4s5G9gF78un1NT2q7DqYas

### Get Playlists Index
GET http://localhost:3000/playlists
Authorization: Bearer {{jwt}}

### Get Playlists Show
GET http://localhost:3000/playlists/8.json
Authorization: Bearer {{jwt}}

### Post Playlists Create
POST http://localhost:3000/playlists
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Retro fusion folk",
  "description": "Who even knows"
}

# ### Patch Playlists Update
# PATCH http://localhost:3000/playlists/7
# Authorization: Bearer {{jwt}}
# Content-Type: application/json

# {
#   "description": "What?"
# }

# ### Delete Playlists Destroy
# DELETE http://localhost:3000/playlists/7
# Authorization: Bearer {{jwt}}



# ### Get Songs Index
# GET http://localhost:3000/songs

# ### Get Songs Show
# GET http://localhost:3000/songs/1

### Post Songs Create
POST http://localhost:3000/songs
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Cake By The Ocean",
  "artist": "DNCE",
  "album": "DNCE",
  "genre": "Pop",
  "url": "https://www.youtube.com/watch?v=vWaRiD5ym74",
  "playlist_id": 8
}

# ### Patch Songs Update
# PATCH http://localhost:3000/songs/8
# Content-Type: application/json

# {
#   "genre": "Dance"
# }

### Delete Songs Destroy
DELETE http://localhost:3000/songs/11
Authorization: Bearer {{jwt}}




### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "John",
  "email": "john@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "alex@test.com",
  "password": "password"
}

# ### Post PlaylistSongs
# POST http://localhost:3000/playlist_songs.json
# Content-Type: application/json

# {
#   "playlist_id": 8,
#   "song_id": 1
# }

### Post UserPlaylist
POST http://localhost:3000/user_playlists
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "email": "joe@test.com",
  "playlist_id": 8
}

### Delete UserPlaylist
DELETE http://localhost:3000/user_playlists/7
Authorization: Bearer {{jwt}}