# Playlist.create(name: "Late night drive", description: "Songs to listen to while taking long drives at nighttime")
# Playlist.create(name: "Angela and Dwight's Wedding", description: "Songs to play on the wedding of the year")
# Playlist.create(name: "Dance Party", description: "Woohoo!!! Everyone dance!!!")

# Song.create(title: "Billie Jean", artist: "Michael Jackson", album: "Thriller", genre: "Pop", url: "https://www.youtube.com/watch?v=Zi_XLOBDo_Y&ab_channel=michaeljacksonVEVO")
# Song.create(title: "Sweet Child o' Mine", artist: "Guns N' Roses", album: "Appetite for Destruction", genre: "Rock", url: "https://www.youtube.com/watch?v=1w7OgIMMRc4")
# Song.create(title: "Y.M.C.A.", artist: "Village People", album: "Cruisin'", genre: "Disco", url: "https://www.youtube.com/watch?v=CS9OO0S5w2k")
# Song.create(title: "Just Dance", artist: "Lady Gaga", album: "The Fame", genre: "Pop", url: "https://www.youtube.com/watch?v=2Abk1jAONjw")
# Song.create(title: "Electric Love", artist: "Børns", album: "Dopamine", genre: "Alternative", url: "https://www.youtube.com/watch?v=VUCuoxOUD6U")
# Song.create(title: "Down", artist: "Marian Hill", album: "ACT ONE", genre: "Alternative", url: "https://www.youtube.com/watch?v=DpMfP6qUSBo")
